# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: YuevUwU
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          filename: assets/my-metrics.svg
          config_timezone: Asia/Taipei
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 365
          plugin_wakatime_languages_ignored: json,yaml,markdown,toml
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os, os-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: YuevUwU
          repositories_forks: yes
          repositories_skipped: Circuit-Miscellaneous-Fabric,DirtToolsMod-Fabric,EnchantedBookSplitter,SCAICT/google-totp
